/**
 * Physical layout of Days Inn Wildwood (551 FL-44), transcribed from the
 * property's front-desk map. Floor 1 rooms are 108 and 110-163; floor 2 rooms
 * are 200-263 plus 265. Second-floor rooms sit directly above their first-floor
 * counterpart (e.g. 134 / 234), so most of the layout is generated by offset.
 */

export type FloorKey = 1 | 2;

const lift = (base: number, floor: FloorKey) => String(floor === 2 ? base + 100 : base);

export type WingRow =
  | { kind: "rooms"; left: string; right: string }
  | { kind: "divider"; label: string };

/** West wing: two rooms per row (odd numbers outside, even numbers inside). */
export function westWing(floor: FloorKey): WingRow[] {
  const rows: WingRow[] = [];
  for (let odd = 111; odd <= 117; odd += 2) {
    rows.push({ kind: "rooms", left: lift(odd, floor), right: lift(odd - 1, floor) });
  }
  rows.push({ kind: "divider", label: "Breezeway · Stairs" });
  for (let odd = 119; odd <= 135; odd += 2) {
    rows.push({ kind: "rooms", left: lift(odd, floor), right: lift(odd - 1, floor) });
  }
  rows.push({ kind: "divider", label: "Breezeway" });
  return rows;
}

/** Rear building: a long double-loaded corridor, evens front / odds back. */
export function rearBuilding(floor: FloorKey): { front: string[]; back: string[] } {
  const front: string[] = [];
  for (let n = 136; n <= 162; n += 2) front.push(lift(n, floor));

  const back: string[] = [];
  for (let n = 137; n <= 161; n += 2) back.push(lift(n, floor));
  back.push(lift(163, floor));
  if (floor === 2) back.push("265");

  return { front, back };
}

export type StripCell =
  | { kind: "room"; number: string }
  | { kind: "space"; label: string; wide?: boolean };

/** The front block by the road: lobby services downstairs, rooms upstairs. */
export function frontBlock(floor: FloorKey): { west: StripCell[]; east: StripCell[] } {
  if (floor === 1) {
    return {
      west: [
        { kind: "space", label: "GM office" },
        { kind: "space", label: "Kitchen" },
        { kind: "space", label: "Lobby / registration", wide: true },
        { kind: "space", label: "Breakfast", wide: true },
        { kind: "space", label: "Security" },
        { kind: "room", number: "108" },
      ],
      east: [{ kind: "space", label: "Swim pool", wide: true }],
    };
  }

  return {
    west: [201, 203, 205, 207, 209].map((n) => ({ kind: "room", number: String(n) }) as StripCell),
    east: [200, 202, 204, 206, 208].map((n) => ({ kind: "room", number: String(n) }) as StripCell),
  };
}

/** Back-of-house rooms at the south end of the west wing. */
export const SERVICE_SPACES = ["Facility", "Guest laundry", "Laundry & storage"];
