// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const isSupabaseConfigured = Boolean(
  (import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"]) &&
  (import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"])
);

function createMockSupabaseClient() {
  const handler: ProxyHandler<any> = {
    get(target, prop, receiver) {
      if (prop === "auth") {
        return {
          onAuthStateChange: (cb: any) => {
            if (typeof cb === "function") {
              // Call with a null session initially to trigger state update
              setTimeout(() => cb("SIGNED_OUT", null), 0);
            }
            return { data: { subscription: { unsubscribe: () => {} } } };
          },
          getSession: () => Promise.resolve({ data: { session: null } }),
          getUser: () => Promise.resolve({ data: { user: null } }),
          signInWithPassword: () => Promise.resolve({ data: {}, error: { message: "Database not configured" } }),
          signUp: () => Promise.resolve({ data: {}, error: { message: "Database not configured" } }),
          signOut: () => Promise.resolve({ error: null }),
        };
      }
      if (prop === "from") {
        return () => {
          const queryBuilder: any = {
            single: () => Promise.resolve({ data: null, error: { message: "Database not configured" } }),
            maybeSingle: () => Promise.resolve({ data: null, error: { message: "Database not configured" } }),
            then: (resolve: any) => resolve({ data: [], error: null }),
          };
          const queryProxy: any = new Proxy(queryBuilder, {
            get(targetObj, method) {
              if (method in targetObj) {
                return targetObj[method];
              }
              return () => queryProxy;
            }
          });
          return queryProxy;
        };
      }
      if (prop === "rpc") {
        return () => {
          const rpcBuilder: any = {
            then: (resolve: any) => resolve({ data: [], error: null }),
          };
          const rpcProxy: any = new Proxy(rpcBuilder, {
            get(targetObj, method) {
              if (method in targetObj) {
                return targetObj[method];
              }
              return () => rpcProxy;
            }
          });
          return rpcProxy;
        };
      }
      if (prop === "channel") {
        return () => {
          const channelBuilder: any = {
            subscribe: () => ({})
          };
          const channelProxy: any = new Proxy(channelBuilder, {
            get(targetObj, method) {
              if (method === "subscribe") {
                return () => ({});
              }
              return () => channelProxy;
            }
          });
          return channelProxy;
        };
      }
      if (prop === "removeChannel") {
        return () => {};
      }
      const val = target[prop];
      if (typeof val === "function") {
        return () => val;
      }
      return new Proxy(() => {}, handler);
    }
  };
  return new Proxy({} as any, handler);
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env["VITE_SUPABASE_URL"] ||
    process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!isSupabaseConfigured) {
    console.warn(
      "[Supabase] Missing Supabase environment variable(s). Connect Supabase in Lovable Cloud. Running in unconfigured/mock mode."
    );
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

