// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const isSupabaseAdminConfigured = Boolean(
  process.env["SUPABASE_URL"] && process.env["SUPABASE_SERVICE_ROLE_KEY"],
);

type AppSupabaseAdminClient = SupabaseClient<Database>;
type MockQueryResult = { data: unknown[]; error: null };
type MockSingleQueryResult = { data: null; error: null };
type MockQueryBuilder = {
  [key: string]: unknown;
  delete: () => MockQueryBuilder;
  eq: () => MockQueryBuilder;
  in: () => MockQueryBuilder;
  insert: () => MockQueryBuilder;
  neq: () => MockQueryBuilder;
  upsert: () => MockQueryBuilder;
  select: () => MockQueryBuilder;
  maybeSingle: () => Promise<MockSingleQueryResult>;
  single: () => Promise<MockSingleQueryResult>;
  then: (resolve: (result: MockQueryResult) => unknown) => unknown;
};

function createMockQueryBuilder(): MockQueryBuilder {
  const builder: MockQueryBuilder = {
    delete: () => builder,
    eq: () => builder,
    in: () => builder,
    insert: () => builder,
    neq: () => builder,
    upsert: () => builder,
    select: () => builder,
    maybeSingle: () => Promise.resolve({ data: null, error: null }),
    single: () => Promise.resolve({ data: null, error: null }),
    then: (resolve) => resolve({ data: [], error: null }),
  };

  return builder;
}

function createMockSupabaseAdminClient(): AppSupabaseAdminClient {
  const handler: ProxyHandler<AppSupabaseAdminClient> = {
    get(target, prop, receiver) {
      if (prop === "auth") {
        return {
          admin: {
            listUsers: () => Promise.resolve({ data: { users: [] } }),
            inviteUserByEmail: () => Promise.resolve({ data: { user: {} } }),
            generateLink: () => Promise.resolve({ data: { properties: { action_link: "" } } }),
          },
        };
      }
      if (prop === "from") {
        return () => createMockQueryBuilder();
      }

      const value = Reflect.get(target, prop, receiver);
      if (typeof value === "function") {
        return () => value;
      }
      return new Proxy({} as AppSupabaseAdminClient, handler);
    },
  };

  return new Proxy({} as AppSupabaseAdminClient, handler) as AppSupabaseAdminClient;
}

function createSupabaseAdminClient(): AppSupabaseAdminClient {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_SERVICE_ROLE_KEY = process.env["SUPABASE_SERVICE_ROLE_KEY"];

  if (!isSupabaseAdminConfigured) {
    console.warn(
      "[Supabase] Missing Supabase admin environment variables. Running in mock admin mode.",
    );
    return createMockSupabaseAdminClient();
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY!),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: AppSupabaseAdminClient | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as AppSupabaseAdminClient, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
}) as AppSupabaseAdminClient;
