// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const isSupabaseConfigured = Boolean(
  (import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"]) &&
  (import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"]),
);

type AppSupabaseClient = SupabaseClient<Database>;
type AuthStateChangeCallback = Parameters<AppSupabaseClient["auth"]["onAuthStateChange"]>[0];
type MockError = { message: string };
type MockQueryResult = { data: unknown[]; error: null };
type MockSingleQueryResult = { data: null; error: MockError };
type MockQueryBuilder = {
  [key: string]: unknown;
  single: () => Promise<MockSingleQueryResult>;
  maybeSingle: () => Promise<MockSingleQueryResult>;
  then: (resolve: (result: MockQueryResult) => unknown) => unknown;
};
type MockChannelBuilder = {
  [key: string]: unknown;
  subscribe: () => object;
};

function createMockQueryBuilder(): MockQueryBuilder {
  const unavailable = { message: "Database not configured" };
  const queryBuilder: MockQueryBuilder = {
    single: () => Promise.resolve({ data: null, error: unavailable }),
    maybeSingle: () => Promise.resolve({ data: null, error: unavailable }),
    then: (resolve) => resolve({ data: [], error: null }),
  };

  const queryProxy = new Proxy(queryBuilder, {
    get(target, property) {
      if (typeof property === "string" && property in target) {
        return target[property];
      }
      return () => queryProxy;
    },
  });

  return queryProxy;
}

function createMockChannelBuilder(): MockChannelBuilder {
  const channelBuilder: MockChannelBuilder = {
    subscribe: () => ({}),
  };

  const channelProxy = new Proxy(channelBuilder, {
    get(target, property) {
      if (property === "subscribe") {
        return target.subscribe;
      }
      return () => channelProxy;
    },
  });

  return channelProxy;
}

function createMockSupabaseClient(): AppSupabaseClient {
  const handler: ProxyHandler<AppSupabaseClient> = {
    get(target, prop, receiver) {
      if (prop === "auth") {
        return {
          onAuthStateChange: (callback: AuthStateChangeCallback) => {
            // Call with a null session initially to trigger state update.
            setTimeout(() => callback("SIGNED_OUT", null), 0);
            return { data: { subscription: { unsubscribe: () => {} } } };
          },
          getSession: () => Promise.resolve({ data: { session: null } }),
          getUser: () => Promise.resolve({ data: { user: null } }),
          getClaims: () => Promise.resolve({ data: { claims: null } }),
          updateUser: () =>
            Promise.resolve({
              data: { user: null },
              error: { message: "Database not configured" },
            }),
          signInWithPassword: () =>
            Promise.resolve({ data: {}, error: { message: "Database not configured" } }),
          signUp: () =>
            Promise.resolve({ data: {}, error: { message: "Database not configured" } }),
          signOut: () => Promise.resolve({ error: null }),
        };
      }
      if (prop === "from" || prop === "rpc") {
        return () => createMockQueryBuilder();
      }
      if (prop === "channel") {
        return () => createMockChannelBuilder();
      }
      if (prop === "removeChannel") {
        return () => undefined;
      }

      const value = Reflect.get(target, prop, receiver);
      if (typeof value === "function") {
        return () => value;
      }
      return new Proxy({} as AppSupabaseClient, handler);
    },
  };

  return new Proxy({} as AppSupabaseClient, handler) as AppSupabaseClient;
}

function createSupabaseClient(): AppSupabaseClient {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env["VITE_SUPABASE_URL"] || process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] || process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!isSupabaseConfigured) {
    console.warn(
      "[Supabase] Missing Supabase environment variable(s). Connect Supabase in Lovable Cloud. Running in unconfigured/mock mode.",
    );
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: AppSupabaseClient | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as AppSupabaseClient, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
}) as AppSupabaseClient;
